server:
  port: 7088
spring:
  application:
      name:test-zuul

zuul:
    routes:
        ms-a:
            path: /msa/**
            serviceId: ms-a
        ms-b:
          path: /msb/**
          serviceId: ms-b